config/routes.rb
Rails.application.routes.draw do
  get 'profile/user_page'
  get 'your_posts' => 'blog_posts#your_posts'
  get 'user_posts' => 'blog_posts#user_posts'
  devise_for :users
  resources :comments
  resources :blog_posts
  
  root 'blog_posts#index'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
    belongs_to :user
    has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :blog_post
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :blog_posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, 
    :password_confirmation, :name, :username, :birthday) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, 
   :password_confirmation, :current_password, :name, :username, :birthday) }
  end
  
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def user_posts
    @user = User.find(params[:id])
  end
  
  def your_posts
    #don't need anything here
    #we'll use association (via current_user)
  end
  
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :blog_post_id, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field cant-see-me">
    <%= f.label :created_at %>
    <%= f.datetime_field :created_at, value: Time.zone %>
  </div>
  <div class="form-group">
    <%= f.label :title, class:"sr-only" %>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <%= f.label :blog_entry, class:"sr-only" %>
    <%= f.text_area :blog_entry, class: "form-control", placeholder: "Entry", rows: 10 %>
  </div>
  <div class="form-group cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ji Blog</h1>

<div class="row">
  <% @blog_posts.each do |blog_post| %>
  <div class='col-md-6'>
    <div class= 'panel panel-default'>
      <div class= 'panel-heading'>
        <h4><%=link_to blog_post.title, blog_post%></h4>
      </div>
      <div class= 'panel-body'>
        by <%= blog_post.author %><br />
        <p><%= blog_post.blog_entry[0..250] %>...</p>
        <p>[<%=link_to 'READ MORE', blog_post%>]</p>
      </div>
      <div class = 'panel-footer'>
        <%=link_to 'Edit', edit_blog_post_path(blog_post), class: 'btn btn-warning' %>
        <%=link_to 'Delete', blog_post, method: :delete, data: { confirm: 'Are you sure?'}, class:'btn btn-danger' %>
      </div>
    </div>
  </div>
  <%end%>
</div>

<br>

<%= link_to 'New Blog post', new_blog_post_path, class: 'btn btn-primary' %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class= 'panel panel-primary'>
  <div class= 'panel-heading'>
    <strong><%= @blog_post.title %></strong>
  </div>
  <div class= 'panel-body'>
    <p>by <strong><%= link_to @blog_post.user.username, user_posts_path(id: @blog_post.user.id) %></strong></p>
    <p><%= @blog_post.blog_entry %></p>
    <p>Posted on: <%= @blog_post.created_at.strftime('%D at %r')%></p>
    <% if current_user.id == @blog_post.user.id %>
    <%= link_to 'Edit Post', edit_blog_post_path(@blog_post), class: 'btn btn-warning' %>
    <%end%>
  </div>
</div>

<div class='panel panel-info'>
  <div class='panel-heading'>
    <strong>Leave a Comment:</strong>
  </div>
  <div class='panel-body'>
    <%= render 'comments/form'%>
  </div>
</div>

<div class='panel panel-default'>
  <div class='panel-heading'>
    <strong>Comments:</strong>
  </div>
  <% @blog_post.comments.each do |comment| %>
    <div class='panel-body'>
      <p><strong><%= link_to comment.user.username, user_posts_path(id: comment.user.id) %></strong> said:</p>
      <p><%= comment.comment_entry %></p>
      <p>Posted on: <%= comment.created_at.strftime('%D %r') %></p>
   </div>
    <%end%>
</div>

  <%= link_to 'Back to Blog', root_path, class: 'btn btn-primary' %>

app/views/blog_posts/user_posts.html.erb
<h1><%=@user.username %>'s Page</h1>

<p><strong>Name:</strong> <%= @user.name %></p>

<p><strong>Birthday:</strong> <%= @user.birthday.strftime("%m/%d/%Y") %></p>

<div class="row">
  <% @user.blog_posts.each do |blog_post| %>
  <div class='col-md-6'>
    <div class= 'panel'>
      <div class= 'panel-heading'>
        <h4><strong><%=link_to blog_post.title, blog_post %></strong></h4>
      </div>
      <div class= 'panel-body'>
        by <strong><%= link_to blog_post.user.username, user_posts_path(id: blog_post.user.id) %></strong><br>
        <p><%= blog_post.blog_entry[0..250] %>...</p>
        <p>[<%=link_to 'READ MORE', blog_post%>]</p>
        <p>Posted on: <%= blog_post.created_at.strftime('%D at %r')%></p>
      </div>
        <% if current_user.id == blog_post.user.id %>
        <%=link_to 'Edit', edit_blog_post_path(blog_post), class: 'btn btn-warning' %>
        <%=link_to 'Delete', blog_post, method: :delete, data: { confirm: 'Are you sure?'}, class:'btn btn-danger' %>
        <%end%>
    </div>
  </div>
  <%end%>
</div>

<br>

app/views/blog_posts/your_posts.html.erb
<h2><%= current_user.username %>'s Posts</h2>
<% current_user.blog_posts.each do |blog_post| %>
<div class="col-md-12">
    <div class= 'panel'>
      <div class= 'panel-heading'>
        <h4><strong><%=link_to blog_post.title, blog_post%></strong></h4>
      </div>
      <div class= 'panel-body'>
        <p>by <strong><%= link_to blog_post.user.username, user_posts_path(id: blog_post.user.id) %></strong></p>
        <p><%= blog_post.blog_entry[0..250] %>...</p>
        <p>[<%=link_to 'READ MORE', blog_post%>]</p>
        <%= blog_post.created_at.strftime('%D at %r')%>
      </div>
        <%=link_to 'Edit', edit_blog_post_path(blog_post), class: 'btn btn-warning' %>
        <%=link_to 'Delete', blog_post, method: :delete, data: { confirm: 'Are you sure?'}, class:'btn btn-danger' %>
    </div>
  </div>
<%end%>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :comment_entry, class:"sr-only" %>
    <%= f.text_area :comment_entry, class: "form-control", placeholder: "Comment", rows: 5 %>
  </div>
  <div class="cant-see-me">
    <%= f.number_field :blog_post_id, value: @blog_post.id %>
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="field cant-see-me">
    <%= f.label :created_at %><br>
    <%= f.datetime_field :created_at, value: Time.zone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<div class='panel panel-info'>
  <div class='panel-header'>
    <h5>Comments</h5>
  </div>
  <div class='panel-body'>
    <p><%= @comment.user.email %> said:</p> 
    <p><%= @comment.comment_entry %></p>
    <p><%= @comment.created_at%></p>
  </div>
</div>

 |
<%= link_to 'Back to Blog', blog_posts_path, class:'btn btn-primary'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ji Blog</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:700,300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top affix-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a><%= link_to "All Posts", root_path, class: 'navbar-brand'%></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to "My Posts", your_posts_path %></li>
        <li><%= link_to "New Post", new_blog_post_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li>
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary"%></li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
            </li>
          </ul>
        <%else%>
          <ul class="nav navbar-nav navbar-right">
            
            <li>
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-danger" %>
            </li>
      </ul>
      <%end%>
      </ul>
      </div>
  </div><!-- /.container-fluid -->
</nav>

<div class= 'container'>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>